version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: teamoctopus/octopus_backend
    env_file: .env
    volumes:
      - static:/app/backend_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: teamoctopus/octopus_frontend_dev
    env_file: .env
    command: cp -r /octopus-front/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend      
  
  gateway:
    image: teamoctopus/octopus_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend      