# Generated by Django 4.1 on 2023-11-28 01:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0005_alter_servicecategory_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FavoritesList",
            new_name="Favorite",
        ),
    ]
