# Generated by Django 4.1 on 2023-12-05 14:09

from django.db import migrations

import users.model_fields
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
